export const jobsJson = {
  jobs_ES: [
    {
      title: 'CEO / Propietario',
      company: 'TNSA Solutions SAS de CV',
      description:
        'CEO y propietario de la empresa, ademas de cabeza creativa y project manager',
      startDate: '2023-09-08',
      finishDate: 'Presente',
      skills: [
         'CEO',
         'Project Management',
         'ASP.NET Core',
         'C#',
         'SOLID',
         'Angular',
         'HTML',
         'SCSS',
         'Typescript',
         'Y Mas',
      ],
    },
    {
      title: 'Freelancer',
      company: '',
      description:
        'Ingeniero freelancer en creacion de aplicaciones web, moviles, websites, y muchas soluciones tecnologicas en el ambito del desarrollo de software',
      startDate: '2019-08',
      finishDate: 'Presente',
      skills: [
        'ASP.NET Core',
        'C#',
        'ASP.NET',
        'SOLID',
        'Angular',
        'HTML',
        'SCSS',
        'Typescript',
        'Y Mas',
      ],
    },
    {
      title: 'SOFTWARE ENGINEER SENIOR CONS I',
      company: 'Integon Service Co',
      description:
        'Ingeniero Senior fullstack en aplicacion CRM especializada en control de leads para ventas de seguros en USA',
      startDate: '2022-07-11',
      finishDate: 'Presente',
      skills: [
        'ASP.NET Core',
        'C#',
        'ASP.NET',
        'SOLID',
        'Angular',
        'HTML',
        'SCSS',
        'Typescript',
        'Y Mas',
      ],
    },
    {
      title: 'SOFTWARE ENGINEER LEAD',
      company: 'IMEX NET Soluciones Globales S de RL de CV',
      description: 'Ingeniero líder y Gerente del área de desarrollo',
      startDate: '2015-10-21',
      finishDate: '2022-07-08',
      skills: [
        'ASP.NET MVC',
        'C#',
        'VB.NET',
        'HTML',
        'CSS',
        'Javascfript',
        'JQuery',
        'Razor Pages',
        'Y Mas',
      ],
    },
    {
      title: 'SOFTWARE ENGINEER',
      company: 'Turbotec SA de CV',
      description:
        'Ingeniero Fullstack en desarrollo de software especializado para uso interno',
      startDate: '2014',
      finishDate: '2015',
      skills: [
        'ASP.NET MVC',
        'C#',
        'VB.NET',
        'HTML',
        'CSS',
        'Javascfript',
        'JQuery',
        'Razor Pages',
        'Y Mas',
      ],
    },
  ],
  jobs_EN: [
    {
      title: 'SOFTWARE ENG-SR CONS I',
      company: 'Integon Service Co',
      description:
        'Senior Fullstack Engineer in CRM Application Apecialized in Leads Control for Insurances Sales in the USA',
      startDate: '2022-07-11',
      finishDate: 'Present',
      skills: [
        'ASP.NET Core',
        'C#',
        'ASP.NET',
        'SOLID',
        'Angular',
        'HTML',
        'SCSS',
        'Typescript',
        'And more',
      ],
    },
    {
      title: 'SOFTWARE ENG LEAD',
      company: 'IMEX NET Soluciones Globales',
      description: 'Lead Engineer and Software Development Manager',
      startDate: '2015-10-21',
      finishDate: '2022-07-08',
      skills: [
        'ASP.NET MVC',
        'C#',
        'VB.NET',
        'HTML',
        'CSS',
        'Javascfript',
        'JQuery',
        'Razor Pages',
        'And more',
      ],
    },
    {
      title: 'SOFTWARE ENGINEER',
      company: 'Turbotec',
      description:
        'Fullstack Engineer in Specialized Software Development for Internal Company Use',
      startDate: '2014',
      finishDate: '2015',
      skills: [
        'ASP.NET MVC',
        'C#',
        'VB.NET',
        'HTML',
        'CSS',
        'Javascfript',
        'JQuery',
        'Razor Pages',
        'And more',
      ],
    },
  ],
};
